const iconMap = {
  A11: 'assets/images/map/knife.svg',
  A12: 'assets/images/map/boxing-single-glove.svg',
  A17: 'assets/images/map/criminal.svg',
  A32: 'assets/images/map/criminal.svg',
  B14: 'assets/images/map/quarrel.svg',
  B18: 'assets/images/map/neighborhood.svg',
  B21: 'assets/images/map/cash-register.svg',
  C16: 'assets/images/map/shoe.svg',
  C22: 'assets/images/map/alarm.svg',
  C29: 'assets/images/map/alarm.svg',
  C31: 'assets/images/map/alarm.svg',
  C36: 'assets/images/map/dollar-symbol.svg',
  D11: 'assets/images/map/car-collision.svg',
  D15: 'assets/images/map/running.svg',
  D21: 'assets/images/map/fire-hydrant.svg',
  D23: 'assets/images/map/parked-car.svg',
  D29: 'assets/images/map/engine-problems.svg',
  E11: 'assets/images/map/drunk-1.svg',
  E12: 'assets/images/map/noise.svg',
  E13: 'assets/images/map/megaphone.svg',
  E14: 'assets/images/map/boxing.svg',
  E21: 'assets/images/map/exclamation.svg',
  F13: 'assets/images/map/danger.svg',
  F16: 'assets/images/map/suspicious.svg',
  F18: 'assets/images/map/rifle.svg',
  F23: 'assets/images/map/danger.svg',
  G13: 'assets/images/map/antibiotic.svg',
  G18: 'assets/images/map/revolver.svg',
  H13: 'assets/images/map/ambulance.svg',
  H14: 'assets/images/map/flammable.svg',
  H24: 'assets/images/map/ring.svg',
  H25: 'assets/images/map/truck.svg',
  H28: 'assets/images/map/networking.svg',
  H31: 'assets/images/map/crutches.svg',
  J11: 'assets/images/map/car-repair.svg',
  J14: 'assets/images/map/burger-and-soda-meal.svg',
  J18: 'assets/images/map/letter.svg',
  J24: 'assets/images/map/police-car.svg',
  J26: 'assets/images/map/shield.svg',
  J28: 'assets/images/map/prisoner.svg',
  J29: 'assets/images/map/worker.svg',
  T10: 'assets/images/map/siren-blue.svg',
};

export default iconMap;